# ワークフローの名前
name: Notion Manga Sync

# ワークフローを実行するタイミング
on:
  # 1時間ごとに自動実行
  schedule:
    - cron: '0 * * * *'
  # Actionsタブから手動で実行できるようにする
  workflow_dispatch:

# 実行する処理内容
jobs:
  build:
    # 実行環境として最新のUbuntuを使用
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 使用するPythonのバージョン

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Pythonスクリプトを実行
      - name: Run Python script
        # ここでGitHub Secretsの値を環境変数としてスクリプトに渡す
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py
